### PR TITLE
Update Logo, Fix login.dart formatting issue, and Create a Splash Screen.

### PR DESCRIPTION
**Pull request by sanehirakenji**
Although there are a lot of file changes, this issue only really changes pubspec.yaml, login.dart, and adds flutter_native_splash.yaml as well as the other images for the login page, so it should not impact us merging wise.

Here is the new Splash Screen (replaces the flutter logo on startup):
Splash Screen

Here is the old login screen:
issue61 before

Here is the updated login screen:
New Login

### CODE REVIEW

**Review by michho8 — APPROVED** [review]
I like the new bold colors of our logo, nice!

**Review by RaphaelBumanlag — APPROVED** [review]
LGTM! Also, what's the difference between the light and dark png? They look the same lol, or is it the case that you need both because some file requires it?

**Comment by sanehirakenji** [comment]
> LGTM! Also, what's the difference between the light and dark png? They look the same lol, or is it the case that you need both because some file requires it?

I think some file requires it? Splash screen added a bunch of images that I don't really understand the purpose of, but it makes the splash screen more personal to our app!

**Review by jiahuiliao — APPROVED** [review]
looks good!

**Pull request merged**
