### PR TITLE
Added navigation to profile pages

### PR DESCRIPTION
**Pull request by RaphaelBumanlag**
Added group member card and widget, removed unused import on some pages, changed some widget parameters to just take a User (i.e. OtherUserProfile(user: user))rather then a User property (i.e. OtherUserProfile(uid: user.id)).

### CODE REVIEW

**Review by sanehirakenji — APPROVED** [review]
Looks fine by me!

**Comment by sanehirakenji** [comment]
Oh wait just make sure its using the current version of main that implemented Riverpod

**Comment by RaphaelBumanlag** [comment]
> Oh wait just make sure its using the current version of main that implemented Riverpod

The one that encapsulates ConnectUniApp() with ProviderScope on main.dart?

**Review by michho8 — APPROVED** [review]
We may want to access the user data using the get methods. For example, not calling `user.pfp` but `user.getPfp()`. It works right now because we didn't declare any instance variables to be private. A future discussion to have. Nice work!

**Review by jiahuiliao — APPROVED** [review]

**Pull request merged**
