### PR TITLE
Sign Up page

### PR DESCRIPTION
**Pull request by michho8**
Sign Up Page:
- four fields for input: username, email, password, and double-check password
- add empty validation by setting states, errors appear when first loading too (would need to [use listener](https://codewithandrea.com/articles/flutter-text-field-form-validation/))
      - checking at each text field for their error message, will show errors initially
- add password validation by comparing both password fields, must be the same
TODO:
- [x] route the "Sign Up" button to the home page or to the profile page?
- [ ] use Listener or another way to only check the fields when the user presses the "Sign Up" button, complete this in Milestone 2 (adding proper functionality)

### CODE REVIEW

**Review by RaphaelBumanlag — APPROVED** [review]
LGTM! for the login, on the next milestone, don't forget to change the .push to .pushReplacement!

**Comment by michho8** [comment]
Oh right, thank you for the reminder!

**Review by jiahuiliao — APPROVED** [review]
nice!

**Review by sanehirakenji — APPROVED** [review]
Nice!

**Pull request merged**
