### PR TITLE
Create message_list and separate mock message DB

### PR DESCRIPTION
**Pull request by michho8**
Separated mock DB and message_list from Message class.

### CODE REVIEW

**Comment by michho8** [comment]
The first four commits were from another branch, don't mind those changes.

**Review by sanehirakenji — APPROVED** [review]
Nice! Looks good!

**Review by jiahuiliao — APPROVED** [review]
looks good!

**Comment by RaphaelBumanlag** [comment]
LGTM!

**Review by RaphaelBumanlag — APPROVED** [review]
LGTM!

**Pull request merged**
