### PR TITLE
Login button able to switch to the Home page

### PR DESCRIPTION
**Pull request by michho8**
[Reopen Login pr](https://github.com/ConnectUni/connectuni/pull/24):
- Decide if we want a "clear" option button
- Has some validation: must enter "correct" in the Email text field and "pass" in the Password text field: which results in a change in the Email text field (will have to replace with a route to the home page)
- Can make text fields larger in width: `padding: const EdgeInsets.symmetric(horizontal: 50.0),`

TODO: 
- [x] route to the Home page for the Login button
- [x] route to the Sign Up page for the Sign Up button - need to uncomment out once signup pr has been merged
- [x] test logo, for now, will need to complete: #25

### CODE REVIEW

**Review by RaphaelBumanlag — APPROVED** [review]
LGTM! Nice work!

**Comment by michho8** [comment]
Currently looks like this:
image

**Review by jiahuiliao — APPROVED** [review]
looks good!

**Review by sanehirakenji — APPROVED** [review]
Nice!

**Comment by michho8** [comment]
With the test logo:
image

**Pull request merged**
