### PR TITLE
Completed friends list page

### PR DESCRIPTION
**Pull request by RaphaelBumanlag**

### CODE REVIEW

**Comment by RaphaelBumanlag** [comment]
Screen Shot 2023-10-04 at 2 11 44 PM

**Review by jiahuiliao — APPROVED** [review]
nice! good work

**Review by sanehirakenji — APPROVED** [review]
Some changes look similar to the last pull request, but I think that should work? Otherwise, good work on the Friends list!

**Review by michho8 — APPROVED** [review]
Nice work, I wasn't aware of the onChanged property before. I'll definitely try use that in my issues!

**Pull request merged**
