### PR TITLE
Added messages that appear if databases are empty.

### PR DESCRIPTION
**Pull request by sanehirakenji**
Made changes to multiple pages that display database items to have text mentioning there are no database items. 
This way our application should no longer have an empty page with nothing on it. The application also now encourages users in this scenario to create an instance of that missing database in order to start filling it up.

### CODE REVIEW

**Comment by sanehirakenji** [comment]
Some of these commits were from my previous implementation of Freezed.

**Review by RaphaelBumanlag — APPROVED** [review]
LGTM!

**Review by michho8 — APPROVED** [review]
I like the implementation, good work!

**Comment by michho8** [comment]
Some merge conflicts need to be fixed though.

**Pull request merged**
